/*
 * Wacht Backend API
 *
 * Backend API for the Wacht platform console
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddOrganizationMemberRequest {
    #[serde(rename = "user_id")]
    pub user_id: String,
    #[serde(rename = "role_id")]
    pub role_id: String,
}

impl AddOrganizationMemberRequest {
    pub fn new(user_id: String, role_id: String) -> AddOrganizationMemberRequest {
        AddOrganizationMemberRequest {
            user_id,
            role_id,
        }
    }
}

