/*
 * Wacht Backend API
 *
 * Backend API for the Wacht platform console
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiAgent {
    /// Agent ID
    #[serde(rename = "id")]
    pub id: String,

    /// Agent name
    #[serde(rename = "name")]
    pub name: String,

    /// Optional description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,

    /// Deployment ID
    #[serde(rename = "deployment_id")]
    pub deployment_id: String,

    /// Generic JSON configuration (contains model, system_prompt, temperature, tools, knowledge_bases, etc.)
    #[serde(rename = "configuration")]
    pub configuration: Value,

    /// Creation timestamp
    #[serde(rename = "created_at")]
    pub created_at: String,

    /// Last update timestamp
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl AiAgent {
    pub fn new() -> AiAgent {
        AiAgent::default()
    }
}
