/*
 * Wacht Backend API
 *
 * Backend API for the Wacht platform console
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiExecutionContext {
    pub id: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub deployment_id: String,
    pub title: String,
    pub current_goal: String,
    pub tasks: Vec<String>,
    pub context_group: Option<String>,
    pub last_activity_at: DateTime<Utc>,
    pub completed_at: Option<DateTime<Utc>>,
    pub execution_state: Option<serde_json::Value>,
    pub status: ExecutionContextStatus,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ExecutionContextStatus {
    Idle,
    Running,
    WaitingForInput,
    Interrupted,
    Completed,
    Failed,
}

impl Default for ExecutionContextStatus {
    fn default() -> Self {
        ExecutionContextStatus::Idle
    }
}

