/*
 * Wacht Backend API
 *
 * Backend API for the Wacht platform console
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ExecutionContextStatus {
    Idle,
    Running,
    WaitingForInput,
    Interrupted,
    Completed,
    Failed,
}

impl Default for ExecutionContextStatus {
    fn default() -> Self {
        ExecutionContextStatus::Idle
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiExecutionContext {
    pub id: String,
    pub created_at: String,
    pub updated_at: String,
    pub deployment_id: String,
    pub title: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_instructions: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub context_group: Option<String>,
    pub last_activity_at: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub execution_state: Option<Value>,
    pub status: ExecutionContextStatus,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub external_context_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub external_resource_metadata: Option<Value>,
}
