/*
 * Wacht Backend API
 *
 * Backend API for the Wacht platform console
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiTool {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "type")]
    pub tool_type: String,
    #[serde(rename = "deployment_id")]
    pub deployment_id: String,
    #[serde(rename = "configuration")]
    pub configuration: Value,
}

impl AiTool {
    pub fn new() -> AiTool {
        AiTool {
            id: String::new(),
            created_at: String::new(),
            updated_at: String::new(),
            name: String::new(),
            description: None,
            tool_type: String::new(),
            deployment_id: String::new(),
            configuration: Value::default(),
        }
    }
}

