/*
 * Wacht Backend API
 *
 * Backend API for the Wacht platform console
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthenticationSettings {
    #[serde(rename = "allow_signups", skip_serializing_if = "Option::is_none")]
    pub allow_signups: Option<bool>,
    #[serde(rename = "require_email_verification", skip_serializing_if = "Option::is_none")]
    pub require_email_verification: Option<bool>,
    #[serde(rename = "password_min_length", skip_serializing_if = "Option::is_none")]
    pub password_min_length: Option<i32>,
    #[serde(rename = "password_require_uppercase", skip_serializing_if = "Option::is_none")]
    pub password_require_uppercase: Option<bool>,
    #[serde(rename = "password_require_numbers", skip_serializing_if = "Option::is_none")]
    pub password_require_numbers: Option<bool>,
    #[serde(rename = "password_require_special", skip_serializing_if = "Option::is_none")]
    pub password_require_special: Option<bool>,
    /// Session timeout in seconds
    #[serde(rename = "session_timeout", skip_serializing_if = "Option::is_none")]
    pub session_timeout: Option<i32>,
    #[serde(rename = "mfa_enabled", skip_serializing_if = "Option::is_none")]
    pub mfa_enabled: Option<bool>,
    #[serde(rename = "allowed_oauth_providers", skip_serializing_if = "Option::is_none")]
    pub allowed_oauth_providers: Option<Vec<AllowedOauthProviders>>,
}

impl AuthenticationSettings {
    pub fn new() -> AuthenticationSettings {
        AuthenticationSettings {
            allow_signups: None,
            require_email_verification: None,
            password_min_length: None,
            password_require_uppercase: None,
            password_require_numbers: None,
            password_require_special: None,
            session_timeout: None,
            mfa_enabled: None,
            allowed_oauth_providers: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AllowedOauthProviders {
    #[serde(rename = "google")]
    Google,
    #[serde(rename = "facebook")]
    Facebook,
    #[serde(rename = "github")]
    Github,
    #[serde(rename = "linkedin")]
    Linkedin,
}

impl Default for AllowedOauthProviders {
    fn default() -> AllowedOauthProviders {
        Self::Google
    }
}

