/*
 * Wacht Backend API
 *
 * Backend API for the Wacht platform console
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct B2BSettings {
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "allow_workspace_creation", skip_serializing_if = "Option::is_none")]
    pub allow_workspace_creation: Option<bool>,
    #[serde(rename = "default_workspace_limit", skip_serializing_if = "Option::is_none")]
    pub default_workspace_limit: Option<i32>,
    #[serde(rename = "require_org_for_signup", skip_serializing_if = "Option::is_none")]
    pub require_org_for_signup: Option<bool>,
    #[serde(rename = "auto_assign_org_role", skip_serializing_if = "Option::is_none")]
    pub auto_assign_org_role: Option<String>,
    #[serde(rename = "auto_assign_workspace_role", skip_serializing_if = "Option::is_none")]
    pub auto_assign_workspace_role: Option<String>,
}

impl B2BSettings {
    pub fn new() -> B2BSettings {
        B2BSettings {
            enabled: None,
            allow_workspace_creation: None,
            default_workspace_limit: None,
            require_org_for_signup: None,
            auto_assign_org_role: None,
            auto_assign_workspace_role: None,
        }
    }
}

