/*
 * Wacht Backend API
 *
 * Backend API for the Wacht platform console
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateAiExecutionContextRequest {
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "context_group", skip_serializing_if = "Option::is_none")]
    pub context_group: Option<String>,
}

impl CreateAiExecutionContextRequest {
    pub fn new() -> CreateAiExecutionContextRequest {
        CreateAiExecutionContextRequest::default()
    }
    
    pub fn with_title(mut self, title: impl Into<String>) -> Self {
        self.title = Some(title.into());
        self
    }
    
    pub fn with_context_group(mut self, group: impl Into<String>) -> Self {
        self.context_group = Some(group.into());
        self
    }
}

