/*
 * Wacht Backend API
 *
 * Backend API for the Wacht platform console
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateAiKnowledgeBaseRequest {
    /// Knowledge base name
    #[serde(rename = "name")]
    pub name: String,

    /// Optional description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,

    /// Generic JSON configuration (contains type, embedding_model, etc.)
    #[serde(rename = "configuration", skip_serializing_if = "Option::is_none")]
    pub configuration: Option<Value>,
}

impl CreateAiKnowledgeBaseRequest {
    pub fn new(name: String) -> CreateAiKnowledgeBaseRequest {
        CreateAiKnowledgeBaseRequest {
            name,
            description: None,
            configuration: None,
        }
    }
}
