/*
 * Wacht Backend API
 *
 * Backend API for the Wacht platform console
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateAiExecutionContextRequest {
    #[serde(rename = "agent_id")]
    pub agent_id: String,
    #[serde(rename = "workflow_id", skip_serializing_if = "Option::is_none")]
    pub workflow_id: Option<String>,
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    #[serde(rename = "session_id", skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
    #[serde(rename = "context", skip_serializing_if = "Option::is_none")]
    pub context: Option<serde_json::Value>,
}

impl CreateAiExecutionContextRequest {
    pub fn new(agent_id: String) -> CreateAiExecutionContextRequest {
        CreateAiExecutionContextRequest {
            agent_id,
            workflow_id: None,
            user_id: None,
            session_id: None,
            context: None,
        }
    }
}

