/*
 * Wacht Backend API
 *
 * Backend API for the Wacht platform console
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateAiToolRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "config")]
    pub config: serde_json::Value,
}

impl CreateAiToolRequest {
    pub fn new(name: String, r#type: Type, config: serde_json::Value) -> CreateAiToolRequest {
        CreateAiToolRequest {
            name,
            description: None,
            r#type,
            config,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "api")]
    Api,
    #[serde(rename = "function")]
    Function,
    #[serde(rename = "webhook")]
    Webhook,
}

impl Default for Type {
    fn default() -> Type {
        Self::Api
    }
}

