/*
 * Wacht Backend API
 *
 * Backend API for the Wacht platform console
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateJwtTemplateRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "claims")]
    pub claims: serde_json::Value,
    #[serde(rename = "ttl")]
    pub ttl: i32,
    #[serde(rename = "is_default", skip_serializing_if = "Option::is_none")]
    pub is_default: Option<bool>,
}

impl CreateJwtTemplateRequest {
    pub fn new(name: String, claims: serde_json::Value, ttl: i32) -> CreateJwtTemplateRequest {
        CreateJwtTemplateRequest {
            name,
            description: None,
            claims,
            ttl,
            is_default: None,
        }
    }
}

