/*
 * Wacht Backend API
 *
 * Backend API for the Wacht platform console
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateAiAgentRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "model")]
    pub model: String,
    #[serde(rename = "system_prompt", skip_serializing_if = "Option::is_none")]
    pub system_prompt: Option<String>,
    #[serde(rename = "temperature", skip_serializing_if = "Option::is_none")]
    pub temperature: Option<f64>,
    #[serde(rename = "max_tokens", skip_serializing_if = "Option::is_none")]
    pub max_tokens: Option<i32>,
    #[serde(rename = "tools", skip_serializing_if = "Option::is_none")]
    pub tools: Option<Vec<String>>,
    #[serde(rename = "knowledge_bases", skip_serializing_if = "Option::is_none")]
    pub knowledge_bases: Option<Vec<String>>,
}

impl CreateAiAgentRequest {
    pub fn new(name: String, model: String) -> CreateAiAgentRequest {
        CreateAiAgentRequest {
            name,
            description: None,
            model,
            system_prompt: None,
            temperature: None,
            max_tokens: None,
            tools: None,
            knowledge_bases: None,
        }
    }
}

