/*
 * Wacht Backend API
 *
 * Backend API for the Wacht platform console
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateAiKnowledgeBaseRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "embedding_model", skip_serializing_if = "Option::is_none")]
    pub embedding_model: Option<String>,
}

impl CreateAiKnowledgeBaseRequest {
    pub fn new(name: String, r#type: Type) -> CreateAiKnowledgeBaseRequest {
        CreateAiKnowledgeBaseRequest {
            name,
            description: None,
            r#type,
            embedding_model: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "vector")]
    Vector,
    #[serde(rename = "graph")]
    Graph,
    #[serde(rename = "hybrid")]
    Hybrid,
}

impl Default for Type {
    fn default() -> Type {
        Self::Vector
    }
}

