/*
 * Wacht Backend API
 *
 * Backend API for the Wacht platform console
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateAiWorkflowRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "trigger_type")]
    pub trigger_type: TriggerType,
    #[serde(rename = "steps")]
    pub steps: Vec<serde_json::Value>,
}

impl CreateAiWorkflowRequest {
    pub fn new(name: String, trigger_type: TriggerType, steps: Vec<serde_json::Value>) -> CreateAiWorkflowRequest {
        CreateAiWorkflowRequest {
            name,
            description: None,
            trigger_type,
            steps,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TriggerType {
    #[serde(rename = "manual")]
    Manual,
    #[serde(rename = "webhook")]
    Webhook,
    #[serde(rename = "schedule")]
    Schedule,
    #[serde(rename = "event")]
    Event,
}

impl Default for TriggerType {
    fn default() -> TriggerType {
        Self::Manual
    }
}

