/*
 * Wacht Backend API
 *
 * Backend API for the Wacht platform console
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateAiToolRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "tool_type")]
    pub tool_type: String,
    #[serde(rename = "configuration")]
    pub configuration: Value,
}

impl CreateAiToolRequest {
    pub fn new(name: String, tool_type: String, configuration: Value) -> CreateAiToolRequest {
        CreateAiToolRequest {
            name,
            description: None,
            tool_type,
            configuration,
        }
    }
}

