/*
 * Wacht Backend API
 *
 * Backend API for the Wacht platform console
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateRoleRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "permissions")]
    pub permissions: Vec<String>,
}

impl CreateRoleRequest {
    pub fn new(name: String, permissions: Vec<String>) -> CreateRoleRequest {
        CreateRoleRequest {
            name,
            permissions,
        }
    }
}
