/*
 * Wacht Backend API
 *
 * Backend API for the Wacht platform console
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentRestrictions {
    #[serde(rename = "allowed_email_domains", skip_serializing_if = "Option::is_none")]
    pub allowed_email_domains: Option<Vec<String>>,
    #[serde(rename = "blocked_email_domains", skip_serializing_if = "Option::is_none")]
    pub blocked_email_domains: Option<Vec<String>>,
    #[serde(rename = "allowed_countries", skip_serializing_if = "Option::is_none")]
    pub allowed_countries: Option<Vec<String>>,
    #[serde(rename = "blocked_countries", skip_serializing_if = "Option::is_none")]
    pub blocked_countries: Option<Vec<String>>,
    #[serde(rename = "ip_whitelist", skip_serializing_if = "Option::is_none")]
    pub ip_whitelist: Option<Vec<String>>,
    #[serde(rename = "ip_blacklist", skip_serializing_if = "Option::is_none")]
    pub ip_blacklist: Option<Vec<String>>,
}

impl DeploymentRestrictions {
    pub fn new() -> DeploymentRestrictions {
        DeploymentRestrictions {
            allowed_email_domains: None,
            blocked_email_domains: None,
            allowed_countries: None,
            blocked_countries: None,
            ip_whitelist: None,
            ip_blacklist: None,
        }
    }
}

