/*
 * Wacht Backend API
 *
 * Backend API for the Wacht platform console
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DisplaySettings {
    #[serde(rename = "logo_url", skip_serializing_if = "Option::is_none")]
    pub logo_url: Option<String>,
    #[serde(rename = "primary_color", skip_serializing_if = "Option::is_none")]
    pub primary_color: Option<String>,
    #[serde(rename = "secondary_color", skip_serializing_if = "Option::is_none")]
    pub secondary_color: Option<String>,
    #[serde(rename = "font_family", skip_serializing_if = "Option::is_none")]
    pub font_family: Option<String>,
    #[serde(rename = "app_name", skip_serializing_if = "Option::is_none")]
    pub app_name: Option<String>,
    #[serde(rename = "welcome_message", skip_serializing_if = "Option::is_none")]
    pub welcome_message: Option<String>,
    #[serde(rename = "support_email", skip_serializing_if = "Option::is_none")]
    pub support_email: Option<String>,
    #[serde(rename = "terms_url", skip_serializing_if = "Option::is_none")]
    pub terms_url: Option<String>,
    #[serde(rename = "privacy_url", skip_serializing_if = "Option::is_none")]
    pub privacy_url: Option<String>,
}

impl DisplaySettings {
    pub fn new() -> DisplaySettings {
        DisplaySettings {
            logo_url: None,
            primary_color: None,
            secondary_color: None,
            font_family: None,
            app_name: None,
            welcome_message: None,
            support_email: None,
            terms_url: None,
            privacy_url: None,
        }
    }
}

