/*
 * Wacht Backend API
 *
 * Backend API for the Wacht platform console
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmailTemplate {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "subject", skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    #[serde(rename = "html_body", skip_serializing_if = "Option::is_none")]
    pub html_body: Option<String>,
    #[serde(rename = "text_body", skip_serializing_if = "Option::is_none")]
    pub text_body: Option<String>,
    #[serde(rename = "variables", skip_serializing_if = "Option::is_none")]
    pub variables: Option<Vec<String>>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl EmailTemplate {
    pub fn new() -> EmailTemplate {
        EmailTemplate {
            name: None,
            subject: None,
            html_body: None,
            text_body: None,
            variables: None,
            updated_at: None,
        }
    }
}

