/*
 * Wacht Backend API
 *
 * Backend API for the Wacht platform console
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmailTemplate {
    pub template_name: String,
    pub template_data: String,
    pub template_from: String,
    pub template_reply_to: String,
    pub template_subject: String,
}

impl EmailTemplate {
    pub fn new() -> EmailTemplate {
        EmailTemplate::default()
    }
}
