/*
 * Wacht Backend API
 *
 * Backend API for the Wacht platform console
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};
use serde_json::Value;

/// Custom signing key configuration
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomSigningKey {
    /// Whether the custom signing key is enabled
    pub enabled: bool,
    /// The key value
    pub key: String,
    /// The algorithm used for signing
    pub algorithm: String,
}

/// JWT template model
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JwtTemplate {
    pub id: String,
    pub name: String,
    /// Token lifetime in seconds
    pub token_lifetime: i64,
    /// Allowed clock skew in seconds
    pub allowed_clock_skew: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_signing_key: Option<CustomSigningKey>,
    /// JWT template configuration
    pub template: Value,
    pub deployment_id: String,
    pub created_at: String,
    pub updated_at: String,
}

impl JwtTemplate {
    pub fn new() -> JwtTemplate {
        JwtTemplate::default()
    }
}
