/*
 * Wacht Backend API
 *
 * Backend API for the Wacht platform console
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KnowledgeBaseDocument {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "knowledge_base_id", skip_serializing_if = "Option::is_none")]
    pub knowledge_base_id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i32>,
    #[serde(rename = "token_count", skip_serializing_if = "Option::is_none")]
    pub token_count: Option<i32>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    #[serde(rename = "uploaded_at", skip_serializing_if = "Option::is_none")]
    pub uploaded_at: Option<String>,
}

impl KnowledgeBaseDocument {
    pub fn new() -> KnowledgeBaseDocument {
        KnowledgeBaseDocument {
            id: None,
            knowledge_base_id: None,
            name: None,
            r#type: None,
            size: None,
            token_count: None,
            status: None,
            uploaded_at: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "pdf")]
    Pdf,
    #[serde(rename = "txt")]
    Txt,
    #[serde(rename = "md")]
    Md,
    #[serde(rename = "docx")]
    Docx,
    #[serde(rename = "html")]
    Html,
}

impl Default for Type {
    fn default() -> Type {
        Self::Pdf
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "processing")]
    Processing,
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "failed")]
    Failed,
}

impl Default for Status {
    fn default() -> Status {
        Self::Processing
    }
}

