/*
 * Wacht Backend API
 *
 * Backend API for the Wacht platform console
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiKnowledgeBaseDocument {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    /// Document title
    #[serde(rename = "title")]
    pub title: String,
    /// Document description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Original file name
    #[serde(rename = "file_name")]
    pub file_name: String,
    /// File size in bytes
    #[serde(rename = "file_size")]
    pub file_size: i64,
    /// MIME type of the file
    #[serde(rename = "file_type")]
    pub file_type: String,
    /// S3 URL of the uploaded file
    #[serde(rename = "file_url")]
    pub file_url: String,
    /// Knowledge base ID
    #[serde(rename = "knowledge_base_id")]
    pub knowledge_base_id: String,
    /// Processing metadata
    #[serde(rename = "processing_metadata", skip_serializing_if = "Option::is_none")]
    pub processing_metadata: Option<Value>,
}

impl AiKnowledgeBaseDocument {
    pub fn new() -> AiKnowledgeBaseDocument {
        AiKnowledgeBaseDocument {
            id: String::new(),
            created_at: String::new(),
            updated_at: String::new(),
            title: String::new(),
            description: None,
            file_name: String::new(),
            file_size: 0,
            file_type: String::new(),
            file_url: String::new(),
            knowledge_base_id: String::new(),
            processing_metadata: None,
        }
    }
}
