/*
 * Wacht Backend API
 *
 * Backend API for the Wacht platform console
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecentSignup {
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "signed_up_at", skip_serializing_if = "Option::is_none")]
    pub signed_up_at: Option<String>,
    #[serde(rename = "signup_method", skip_serializing_if = "Option::is_none")]
    pub signup_method: Option<SignupMethod>,
    #[serde(rename = "organization", skip_serializing_if = "Option::is_none")]
    pub organization: Option<Box<models::RecentSignupOrganization>>,
}

impl RecentSignup {
    pub fn new() -> RecentSignup {
        RecentSignup {
            user_id: None,
            email: None,
            username: None,
            signed_up_at: None,
            signup_method: None,
            organization: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SignupMethod {
    #[serde(rename = "email")]
    Email,
    #[serde(rename = "google")]
    Google,
    #[serde(rename = "facebook")]
    Facebook,
    #[serde(rename = "github")]
    Github,
    #[serde(rename = "linkedin")]
    Linkedin,
}

impl Default for SignupMethod {
    fn default() -> SignupMethod {
        Self::Email
    }
}

