/*
 * Wacht Backend API
 *
 * Backend API for the Wacht platform console
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OauthCredentials {
    pub client_id: String,
    pub client_secret: String,
    pub redirect_uri: String,
    pub scopes: Vec<String>,
}

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SocialConnection {
    #[serde(rename = "provider", skip_serializing_if = "Option::is_none")]
    pub provider: Option<Provider>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "user_defined_scopes", skip_serializing_if = "Option::is_none")]
    pub user_defined_scopes: Option<Vec<String>>,
    #[serde(rename = "credentials", skip_serializing_if = "Option::is_none")]
    pub credentials: Option<OauthCredentials>,
}

impl SocialConnection {
    pub fn new() -> SocialConnection {
        SocialConnection {
            provider: None,
            enabled: None,
            user_defined_scopes: None,
            credentials: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Provider {
    #[serde(rename = "x_oauth")]
    XOauth,
    #[serde(rename = "github_oauth")]
    GithubOauth,
    #[serde(rename = "gitlab_oauth")]
    GitlabOauth,
    #[serde(rename = "google_oauth")]
    GoogleOauth,
    #[serde(rename = "facebook_oauth")]
    FacebookOauth,
    #[serde(rename = "microsoft_oauth")]
    MicrosoftOauth,
    #[serde(rename = "linkedin_oauth")]
    LinkedinOauth,
    #[serde(rename = "discord_oauth")]
    DiscordOauth,
    #[serde(rename = "apple_oauth")]
    AppleOauth,
}

impl Default for Provider {
    fn default() -> Provider {
        Self::GoogleOauth
    }
}

