/*
 * Wacht Backend API
 *
 * Backend API for the Wacht platform console
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OauthCredentials {
    pub client_id: String,
    pub client_secret: String,
    pub redirect_uri: String,
    pub scopes: Vec<String>,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SocialConnectionProvider {
    XOauth,
    GithubOauth,
    GitlabOauth,
    GoogleOauth,
    FacebookOauth,
    MicrosoftOauth,
    LinkedinOauth,
    DiscordOauth,
    AppleOauth,
}

impl Default for SocialConnectionProvider {
    fn default() -> SocialConnectionProvider {
        Self::GoogleOauth
    }
}

/// Backwards-compatible alias for the social connection provider enum.
pub type Provider = SocialConnectionProvider;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentSocialConnection {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "deployment_id", skip_serializing_if = "Option::is_none")]
    pub deployment_id: Option<String>,
    #[serde(rename = "provider", skip_serializing_if = "Option::is_none")]
    pub provider: Option<SocialConnectionProvider>,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "credentials", skip_serializing_if = "Option::is_none")]
    pub credentials: Option<OauthCredentials>,
}

impl DeploymentSocialConnection {
    pub fn new() -> DeploymentSocialConnection {
        DeploymentSocialConnection::default()
    }
}

// Legacy SocialConnection model for backwards compatibility
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SocialConnection {
    #[serde(rename = "provider", skip_serializing_if = "Option::is_none")]
    pub provider: Option<SocialConnectionProvider>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(
        rename = "user_defined_scopes",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_defined_scopes: Option<Vec<String>>,
    #[serde(rename = "credentials", skip_serializing_if = "Option::is_none")]
    pub credentials: Option<OauthCredentials>,
}

impl SocialConnection {
    pub fn new() -> SocialConnection {
        SocialConnection {
            provider: None,
            enabled: None,
            user_defined_scopes: None,
            credentials: None,
        }
    }
}

/// A user's social (OAuth) connection, as returned by
/// `GET /users/{user_id}/social-connections`. Mirrors the backend `SocialConnection`
/// model field-for-field (ids and timestamps are emitted as strings).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserSocialConnection {
    pub id: String,
    pub created_at: String,
    pub updated_at: String,
    pub user_id: String,
    pub user_email_address_id: String,
    pub provider: SocialConnectionProvider,
    pub email_address: String,
    pub access_token: String,
    pub refresh_token: String,
}
