/*
 * Wacht Backend API
 *
 * Backend API for the Wacht platform console
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateOrganizationMemberRequest {
    #[serde(rename = "role_ids", skip_serializing_if = "Option::is_none")]
    pub role_ids: Option<Vec<String>>,
    #[serde(rename = "public_metadata", skip_serializing_if = "Option::is_none")]
    pub public_metadata: Option<serde_json::Value>,
}

impl UpdateOrganizationMemberRequest {
    pub fn new() -> UpdateOrganizationMemberRequest {
        UpdateOrganizationMemberRequest {
            role_ids: None,
            public_metadata: None,
        }
    }
}
