/*
 * Wacht Backend API
 *
 * Backend API for the Wacht platform console
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdatePasswordRequest {
    #[serde(rename = "current_password")]
    pub current_password: String,
    #[serde(rename = "new_password")]
    pub new_password: String,
}

impl UpdatePasswordRequest {
    pub fn new(current_password: String, new_password: String) -> UpdatePasswordRequest {
        UpdatePasswordRequest {
            current_password,
            new_password,
        }
    }
}

