/*
 * Wacht Backend API
 *
 * Backend API for the Wacht platform console
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateOrganizationMemberRequest {
    #[serde(rename = "role_id")]
    pub role_id: String,
}

impl UpdateOrganizationMemberRequest {
    pub fn new(role_id: String) -> UpdateOrganizationMemberRequest {
        UpdateOrganizationMemberRequest {
            role_id,
        }
    }
}

