/*
 * Wacht Backend API
 *
 * Backend API for the Wacht platform console
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdatePasswordRequest {
    #[serde(rename = "new_password")]
    pub new_password: String,
    #[serde(rename = "skip_password_check", skip_serializing_if = "Option::is_none")]
    pub skip_password_check: Option<bool>,
}

impl UpdatePasswordRequest {
    pub fn new(new_password: String) -> UpdatePasswordRequest {
        UpdatePasswordRequest {
            new_password,
            skip_password_check: None,
        }
    }
}

