/*
 * Wacht Backend API
 *
 * Backend API for the Wacht platform console
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserPhone {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "user_id")]
    pub user_id: String,
    #[serde(rename = "phone_number")]
    pub phone_number: String,
    #[serde(rename = "country_code")]
    pub country_code: String,
    #[serde(rename = "verified")]
    pub verified: bool,
    #[serde(rename = "verified_at")]
    pub verified_at: String,
}

impl UserPhone {
    pub fn new() -> UserPhone {
        UserPhone {
            id: String::new(),
            created_at: String::new(),
            updated_at: String::new(),
            user_id: String::new(),
            phone_number: String::new(),
            country_code: String::new(),
            verified: false,
            verified_at: String::new(),
        }
    }
}
