/*
 * Wacht Backend API
 *
 * Backend API for the Wacht platform console
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserEmail {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "deployment_id")]
    pub deployment_id: String,
    #[serde(rename = "user_id")]
    pub user_id: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "is_primary")]
    pub is_primary: bool,
    #[serde(rename = "verified")]
    pub verified: bool,
    #[serde(rename = "verified_at")]
    pub verified_at: String,
    #[serde(rename = "verification_strategy")]
    pub verification_strategy: String,
}

impl UserEmail {
    pub fn new() -> UserEmail {
        UserEmail {
            id: String::new(),
            created_at: String::new(),
            updated_at: String::new(),
            deployment_id: String::new(),
            user_id: String::new(),
            email: String::new(),
            is_primary: false,
            verified: false,
            verified_at: String::new(),
            verification_strategy: String::new(),
        }
    }
}
