/*
 * Wacht Backend API
 *
 * Backend API for the Wacht platform console
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct User {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    #[serde(rename = "first_name", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    #[serde(rename = "last_name", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(
        rename = "profile_picture_url",
        skip_serializing_if = "Option::is_none"
    )]
    pub profile_picture_url: Option<String>,
    #[serde(
        rename = "primary_email_address",
        skip_serializing_if = "Option::is_none"
    )]
    pub primary_email_address: Option<String>,
    #[serde(
        rename = "primary_phone_number",
        skip_serializing_if = "Option::is_none"
    )]
    pub primary_phone_number: Option<String>,
}

impl User {
    pub fn new() -> User {
        User {
            id: None,
            created_at: None,
            updated_at: None,
            first_name: None,
            last_name: None,
            username: None,
            profile_picture_url: None,
            primary_email_address: None,
            primary_phone_number: None,
        }
    }
}
