/*
 * Wacht Backend API
 *
 * Backend API for the Wacht platform console
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkspaceRole {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "permissions")]
    pub permissions: Vec<String>,
    #[serde(rename = "is_deployment_level")]
    pub is_deployment_level: bool,
}

impl WorkspaceRole {
    pub fn new() -> WorkspaceRole {
        WorkspaceRole {
            id: String::new(),
            created_at: String::new(),
            updated_at: String::new(),
            name: String::new(),
            permissions: Vec::new(),
            is_deployment_level: false,
        }
    }
}

